name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get-dependencies
      run: |
        sudo mkdir -p /usr/include/nlohmann
        sudo curl -L https://github.com/nlohmann/json/releases/download/v3.7.3/json.hpp -o /usr/include/nlohmann/json.hpp
    - name: test
      run: make
